services:     
  skylink:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    tty: true
    container_name: skylink
    hostname: skylink
    restart: unless-stopped
    environment:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      - READSB_ENABLE_API=true
      - GRAPHS1090_DISABLE=false
      - MAX_GLOBE_HISTORY=2	
      - READSB_EXTRA_ARGS=
        --quiet
        --write-json-globe-index
        --heatmap=0
        --write-globe-history /var/globe_history --json-trace-interval 60
        --tar1090-use-api
        --net-api-port unix:/run/readsb/api.sock
        --net-ingest
        --net-receiver-id
        --net-buffer 4
        --net-connector-delay 5
      - READSB_NET_CONNECTOR=192.168.11.10,30004,beast_in;
      #192.168.11.10,30005,beast_in;
      # TAR1090 (Map Web Page) parameters:
      - TAR1090_BINGMAPSAPIKEY=Alq7RH7qHgMmDk_L707lgKj7MNNQCwLiUSpauLs96M45remQCSBVA4Un5MBJA-Gc
      - TAR1090_PAGETITLE=Skylink
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_MAPTYPE_TAR1090=Stadia_Alidade_Smooth
      - TAR1090_MAPDIM=false
      - GZIP_LVL=1
      - TAR1090_FLIGHTAWARELINKS=true
      - TAR1090_ENABLE_AC_DB=true
      - UPDATE_TAR1090=true
      - TAR1090_USEROUTEAPI=false
      - GRAPHS1090_DARKMODE=false
    volumes:
      - ./data/graphs1090:/var/lib/collectd
      - ./local/skylink-lc2:/var/tar1090_git_source
      - ./data/globe_history:/var/globe_history
      - /proc/diskstats:/proc/diskstats:ro
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=2G
      - /var/log:size=64M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 30004:30004/tcp
      - 30104:30104/tcp
      - 33003:30003
      - 32006:30006
      - 33005:30005/tcp
      - 31787:80
    networks:
      - skynet
    security_opt:
      - apparmor:unconfined      
networks:
  skynet:
    name: skynet
    external: true
