services:
  skylink-core:
    image: skylink-core:v2
    container_name: skylink-core
    restart: unless-stopped
    init: true
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    environment:
      - RUST_LOG=info
      - BEAST_CONNECT=skylink:30005
      - API_PORT=19180
    ports:
      - "19180:19180"
    networks:
      - skynet

networks:
  skynet:
    external: true
