# tar1090 FE on :31790
server {
    listen 80;
    server_name skylink-test-corev3.hpradar.com;

    root /var/www/tar1090;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /data/ {
        proxy_pass http://skylink-core:19180/data/;
    }

    location /re-api/ {
        proxy_pass http://skylink-core:19180/re-api/;
    }

    location /stats {
        proxy_pass http://skylink-core:19180/stats;
    }

    location /ws {
        proxy_pass http://skylink-core:19180/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}

# readsb-protobuf webapp on :31791
server {
    listen 81;

    root /var/www/protobuf;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /data/ {
        proxy_pass http://skylink-core:19180/data/;
    }

    location /re-api/ {
        proxy_pass http://skylink-core:19180/re-api/;
    }

    location /chunks/ {
        proxy_pass http://skylink-core:19180/re-api/?binCraft&;
    }

    location /ws {
        proxy_pass http://skylink-core:19180/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
