server {
    listen 80;
    server_name skylink-test-corev3.hpradar.com;

    # Static FE files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # API proxy to skylink-core
    location /data/ {
        proxy_pass http://skylink-core:19180/data/;
        proxy_set_header Host $host;
    }

    location /re-api/ {
        proxy_pass http://skylink-core:19180/re-api/;
        proxy_set_header Host $host;
    }

    location /stats {
        proxy_pass http://skylink-core:19180/stats;
    }

    # WebSocket
    location /ws {
        proxy_pass http://skylink-core:19180/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
